### ISSUE TITLE
[Widget] Chart Widget 확인 및 추가

### ISSUE THREAD

**Issue by korca0220** [Fun-d-6th-Stock-King/should-have-bought-app#3]
# ToDo
- [ ] 차트 라이브러리 기능 확인 
- [ ] 현재까지 기획 된 차트부분 Semi-Develop(추후 기능 수정/보완 하여 정식적으로 사용)
- [ ] 차트 현실성 확인 필요(10년전, 5년전, 1년전 차트그리기)

# 참괴 링크
> https://pub.dev/packages/syncfusion_flutter_charts
> https://pub.dev/packages/fl_chart

**Comment by Soobinnn** [comment]
완료
